version: '3'

services:
  flask_app:
    build: ./flask
    volumes:
      - ./flask:/app
    ports:
      - "8000:8000"

  nginx:
    build: ./nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - flask_app
